ALTER TABLE routing_edges ADD COLUMN IF NOT EXISTS boat_cost DOUBLE PRECISION NOT NULL DEFAULT 1.0;
ALTER TABLE routing_edges ADD COLUMN IF NOT EXISTS boat_reverse_cost DOUBLE PRECISION NOT NULL DEFAULT 1.0;
ALTER TABLE routing_edges ADD COLUMN IF NOT EXISTS wagon_cost DOUBLE PRECISION NOT NULL DEFAULT 1.0;
ALTER TABLE routing_edges ADD COLUMN IF NOT EXISTS wagon_reverse_cost DOUBLE PRECISION NOT NULL DEFAULT 1.0;

ALTER TABLE city ADD COLUMN IF NOT EXISTS harbor BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE city ADD COLUMN IF NOT EXISTS boat_stock INT NOT NULL DEFAULT 0;
ALTER TABLE city ADD COLUMN IF NOT EXISTS wagon_stock INT NOT NULL DEFAULT 0;

ALTER TABLE agent ADD COLUMN IF NOT EXISTS vehicle_id BIGINT;

CREATE TABLE IF NOT EXISTS vehicle (
    id BIGSERIAL PRIMARY KEY,
    type VARCHAR(16) NOT NULL,
    location geometry(Point, 4326),
    speed DOUBLE PRECISION NOT NULL DEFAULT 1.0,
    occupant_id BIGINT,
    home_city_id BIGINT
);

CREATE INDEX IF NOT EXISTS vehicle_occupant_idx ON vehicle (occupant_id);
CREATE INDEX IF NOT EXISTS vehicle_location_idx ON vehicle USING GIST (location);
